version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: /bin/bash -c "npm install && npm run dev"
